env:
  browser: true
  es2021: true
  node: true
extends:
  - "plugin:react/recommended"
  - google
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  require-jsdoc: off
  react/prop-types: off
  react/display-name: off
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  max-len:
    - warn
    - code: 140
  brace-style:
    - warn
    - stroustrup
    - allowSingleLine: true
  object-curly-spacing:
    - warn
    - always
  operator-linebreak:
    - warn
    - before