import image from '@/assets/images/CourseLanding/sessionIMG_9.png'

export const playlists = [
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 1,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 2,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 3,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 4,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 5,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 6,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 7,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts.',
    video: image,
    name: 'Justin Timberlake ',
    id: 8,
  },
  {
    date: 'CREATIVE VERSALITY  •  10 MINS',
    title: 'Starting Out',
    description: 'How do you tune our your critics, your doubts. ',
    video: image,
    name: 'Justin Timberlake ',
    id: 9,
  },
]
