export const icons = {
  error: require('./error.png'),
  eye: require('./eye.png'),
  forwardArrow: require('./arrow.png'),
  unCheck: require('./checkboxUn.png'),
  apple: require('./apple.png'),
  google: require('./google.png'),
  facebook: require('./facebook.png'),
  appleIcon: require('./appleIcon.png'),
  googleIcon: require('./googleIcon.png'),
  facebookIcon: require('./fbIcon.png'),
  rectangle: require('./Rectangle.png'),
  openEye: require('./open_eye.png'),
  checkBox: require('./checkbox.png'),
  bgImageSignIn: require('./BgImageSignIn.png'),
  APay: require('./APay.png'),
  GPay: require('./GPay.png'),
  downArrow: require('./downwardArrow.png'),
  cvcFrame: require('./cvcFrame.png'),
  visa: require('./visa.png'),
  masterCard: require('./Mastercard.png'),
  americanExpress: require('./AmericanExpress.png'),
  discover: require('./Discover.png'),
  forwardArr: require('./forwardArrow.png'),
  starMedal: require('./starMedal.png'),
  close: require('./close.png'),
  saveTag: require('./saveTag.png'),
  oppDownward: require('./oppDownward.png'),
  add: require('./add.png'),
  image1: require('./image1.png'),
  image2: require('./image2.png'),
  notification: require('./Notification.png'),
  edit: require('./edit.png'),

}
