import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: 'red',
  },
  textInputStyle: {
    height: 44,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: '#FFFFFF',
    elevation: 1,
    borderRadius: 8,
    padding: 10,
    color: '#000000',
  },
  bottomtxtStyle: {
    color: '#888888',
    fontWeight: '400',
    fontSize: 12,
  },
  bottomViewStyle: {
    flexDirection: 'row',
    marginVertical: 15,
    width: '30%',
    paddingStart: 10,
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  width_55P: { width: '55%' },
  width_50P: { width: '50%' },
  poweredBy: { textAlign: 'center', color: '#888888' },
  stripeText: { fontWeight: 'bold', color: '#888888' },
  byConfirmText: {
    fontSize: 16,
    color: '#535353',
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 5,
  },
  alignSelf_center: { alignSelf: 'center' },
  subscribeText: {
    fontSize: 16,
    color: '#888888',
    fontFamily: 'Helvet_medium',
  },
  subscribeBtn: {
    backgroundColor: '#EDEDED',
    alignItems: 'center',
    paddingVertical: 16,
    borderRadius: 3,
    marginVertical: 30,
  },
  headingText: {
    fontWeight: 'bold',
    color: '#888888',
    fontSize: 16,
  },
  zipView: {
    flexDirection: 'row',
    height: 44,
    marginVertical: 0,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: '#FFFFFF',
    elevation: 1,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    padding: 10,
  },
  dropDownStyle: {
    position: 'absolute',
    width: 13,
    height: 8,
    right: 12,
    top: 20,
  },
  dropDownIcon: {
    width: 13,
    height: 8,
    right: 12,
  },
  zipTextInputStyle: { width: '100%', color: '#000000' },
  countryTxtinputStyle: { width: '95%', color: '#000000' },
  nameOnCardTxtinput: { width: '100%', color: '#000000', padding: 10 },
  countryView: {
    flexDirection: 'row',
    height: 44,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: '#FFFFFF',
    elevation: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    padding: 10,
    borderBottomWidth: 0,
  },
  mTop_20: { marginTop: 20 },
  nameOnCardView: {
    flexDirection: 'row',
    height: 44,
    marginVertical: 0,
    borderWidth: 1,
    borderColor: '#EDEDED',
    // elevation: 1,
    elevation: 0.5,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  cardFieldView: {
    flexDirection: 'row',
    // height: 44,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: '#FFFFFF',
    elevation: 0.5,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomWidth: 0,
    paddingTop: 1,
  },
  lineView: {
    height: 2,
    borderBottomWidth: 1,
    borderColor: '#EDEDED',
    width: '32%',
  },
  payWithCard: {
    color: '#888888',
    marginHorizontal: 10,
    fontSize: 14,
  },
  payWithCardView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    marginVertical: 20,
  },
  paymentScreenBtn: {
    backgroundColor: 'black',
    alignItems: 'center',
    marginVertical: 8,
    paddingVertical: 5,
    borderRadius: 3,
  },
  btnImage: {
    height: 40,
    width: 60,
  },
  secondView: {
    backgroundColor: 'white',
    padding: 24,
  },
  subscribeUpperText: {
    fontSize: 22,
    color: 'black',
    fontWeight: 'bold',
  },
  upperDollarView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  dollarTxt: {
    fontSize: 27,
    color: 'black',
    textAlign: 'center',
    paddingTop: 10,
    fontWeight: 'bold',
  },
  perMonth: {
    color: '#888888',
    marginLeft: 10,
  },
  detailsView: {
    backgroundColor: '#FFF200',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRadius: 5,
    marginVertical: 18,
  },
  detailsBtnView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  detailsTxt: {
    color: 'black',
    fontSize: 16,
    // fontWeight: '400',
    fontFamily: 'Helvet_medium',
  },
  forwardArrow: {
    width: 16,
    height: 10,
    marginLeft: 5,
  },
  keepSekingtext: {
    color: '#888888',
    textAlign: 'center',
  },
  toggleTrue: {
    alignSelf: 'center',
    // backgroundColor: '#EDEDED',
    backgroundColor: '#F5F5F5',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 30,
    height: 210,
  },
  priceTxt: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  subtotalTxt: {
    fontWeight: '400',
    fontSize: 16,
  },
  lightClrText: {
    color: '#535353',
    fontSize: 14,
    opacity: 0.6,
  },
  quantityText: {
    fontSize: 14,
    marginHorizontal: 7,
  },
  withoutImageView: {
    width: '70%',
    borderBottomWidth: 1,
    borderColor: '#C0C0C0',
  },
  ViewWithBottomLine: {
    borderBottomWidth: 1,
    borderColor: '#C0C0C0',
    paddingBottom: 8,
  },
  saveTxt: {
    color: 'black',
    fontSize: 16,
    fontWeight: '900',
  },
  savetagicon: {
    width: 28,
    height: 28,
  },
  closeIcon: {
    width: 14,
    height: 14,
    marginLeft: 5,
  },
  black_14: {
    color: '#000000',
    fontSize: 14,
  },
  totalDueTodayView: {
    flexDirection: 'row',
    marginTop: 18,
  },
  emptyView: {
    width: '15%',
    borderBottomWidth: 0,
  },
  addPromoTxtInput: {
    height: 40,
    borderWidth: 1,
    borderColor: '#EDEDED',
    backgroundColor: '#FFFFFF',
    elevation: 0.5,
    borderRadius: 8,
    fontSize: 16,
    padding: 10,
    color: '#000000',
  },
  saveBtnView: {
    backgroundColor: '#FFF200',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 5,
  },
  cardStyle: {
    width: '100%',
    height: 44,
  },
  btnOrTextInput: {
    width: '87%',
    borderBottomWidth: 1,
    borderColor: '#C0C0C0',
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  row_mt_10: {
    flexDirection: 'row',
    marginTop: 10,
  },
  row_mt_18: {
    flexDirection: 'row',
    marginTop: 18,
  },
  toggleFalse: {
    alignSelf: 'center',
    // backgroundColor: '#EDEDED',
    backgroundColor: '#F5F5F5',
    width: '100%',
    paddingVertical: 20,
    paddingHorizontal: 24,
    height: 250,
  },
  starMedal: {
    width: 40,
    height: 40,
  },
  width_15P: {
    width: '15%',
  },
  flex_row: {
    flexDirection: 'row',
  },
  width_70P: {
    width: '70%',
  },
  toggleBtnStyle: {
    width: 13,
    height: 8,
    marginLeft: 5,
  },
  toggleBtnView: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignSelf: 'flex-end',
    alignItems: 'center',
  },
  minH_100P: {
    minHeight: '100%',
  },
  scrollViewStyle: {
    // backgroundColor: '#EDEDED',
    backgroundColor: '#F5F5F5',
    marginBottom: 40,
  },
})
